import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import anime from 'https://cdn.skypack.dev/animejs@3.2.2';
import './styles.css';

const agents = {
  GARA:{label:'General Affairs', code:'G', color:'#ff5c35', dark:'#2a1513', tagline:'The operational layer for a calmer workplace.', desc:'From first request to final approval, GARA keeps every office operation moving with context, controls, and a clear human handoff.', tabs:[['C1','Pengadaan & Stok','Purchase requests, reorder points, and approval queues'],['C2','Vendor','Vendor intake, quotes, and sourcing'],['C3','Aset & Inventaris','Asset records, movement, and lifecycle'],['C4','Booking Fasilitas','Rooms, equipment, and shared facilities'],['C5','Tiket Internal','Internal service requests and triage'],['C6','Perjalanan Dinas','Travel requests and trip coordination'],['C7','Digest Keamanan','Security digests and operational awareness'],['C8','Pengetahuan & Kepatuhan','Policies, knowledge, and compliance']],
  workflow:['Capture the request','JDI Internal AI drafts & analyses','Team reviews the decision','Action is logged with provenance'], proof:['8 operational flows','T1 → T3 controls','Human approval required']},
  FINA:{label:'Finance Intelligence', code:'F', color:'#9b8cff', dark:'#17142c', tagline:'The control room for every finance decision.', desc:'FINA turns messy documents into deterministic matches, review-ready approvals, and an auditable trail—without executing a payment.', tabs:[['F1','Faktur & PO Matching','OCR intake, extraction, and deterministic matching'],['F2','Persetujuan Faktur','Approval cards, exceptions, and payment readiness'],['F3','Struk & Kebijakan','Receipt capture and policy checks'],['F4','Rekonsiliasi & AP/AR','Reconciliation across accounts payable and receivable'],['F5','Kebijakan & Lingkup','Finance rules, guardrails, and operating scope']], workflow:['Intake PDF, JPG, or PNG','Extract fields with local OCR','Match against PO data','Human signs off—never autopay'], proof:['±1% match tolerance','Local OCR pipeline','No real payment execution']},
  SARA:{label:'Sales / BD', code:'S', color:'#35c89a', dark:'#10251f', tagline:'A sharper signal from first hello to closed loop.', desc:'SARA turns conversations into structured pipeline, gives sellers useful next steps, and keeps negotiation, credit, and contracts in human hands.', tabs:[['S1','Prospecting & Lead','Capture leads and suggest hot / warm / cold segments'],['S2','Qualification & Proposal','Qualify needs and shape a proposal'],['S3','Negosiasi & Diskon','Track negotiation while protecting approval boundaries'],['S4','Order & Kredit','Coordinate orders, credit checks, and sign-off'],['S5','After-Sales & Pipeline','Keep customers moving and pipeline visible']], workflow:['Capture the conversation','JDI Internal AI suggests a signal','Sales shapes the next move','Human owns the commercial decision'], proof:['CRM in the same interaction','Configurable signals','No final discount or credit decision']}
};

function App(){
 const [active,setActive]=useState('GARA'); const [tab,setTab]=useState(0); const [proofOpen,setProofOpen]=useState(null); const [logOpen,setLogOpen]=useState(false); const [modal,setModal]=useState(null); const a=agents[active];
 const goHome=()=>{setActive('GARA');setTab(0);setProofOpen(null);setLogOpen(false);setModal(null);window.scrollTo({top:0,behavior:'smooth'})};
 const tableSets={GARA:[
  [['NO. PR','ITEM / VENDOR','OWNER','VALUE','STATUS'],[['PR-1001','Toner HP · CV Mitra Kantor','GA Procurement','Rp 4.800.000','MENUNGGU'],['PR-1002','Antivirus endpoint · PT Aman Digital','IT + GA','Rp 27.500.000','REVIEW'],['PR-1003','Cleaning service · PT Bersih Utama','Facilities','Rp 6.200.000','DISETUJUI']]],
  [['VENDOR','CATEGORY','LAST QUOTE','RISK','NEXT ACTION'],[['V-019 · CV Arunika Office','Office supplies','Rp 4,8 jt · 02 Sep','LOW','Request refresh'],['V-044 · PT Aman Digital','IT services','Rp 27,5 jt · 05 Sep','MEDIUM','Need 2nd quote'],['V-031 · Bersih Utama','Facilities','Contract renewal','LOW','Keep incumbent']]],
  [['ASSET ID','ASSET / LOCATION','CONDITION','OWNER','ACTION'],[['AST-0081','Projector Epson · R. Melati','GOOD','Events','Keep'],['AST-0044','Standing desk · Floor 3','REPAIR','People Ops','Schedule service'],['AST-0112','MacBook Pro · R. Anggrek','ASSIGNED','Design','Audit 12 Sep']]],
  [['BOOKING','FACILITY','REQUESTER','SLOT','STATUS'],[['BK-071','Boardroom A · 12 seats','Nadia / Legal','10 Sep · 14:00','CONFIRMED'],['BK-072','Event hall + AV','GA Events','13 Sep · 09:00','CONFLICT'],['BK-073','Focus room 2','Rizky / Finance','11 Sep · 11:30','HELD']]],
  [['TICKET','REQUEST','PRIORITY','ASSIGNEE','SLA'],[['TCK-188','Replace lobby signage','P2','Facilities','18h left'],['TCK-189','VPN access for contractor','P1','IT Support','4h left'],['TCK-190','Kitchen water filter','P3','Office Admin','2d left']]],
  [['TRIP','TRAVELER','ROUTE','DATES','STATUS'],[['TRV-041','Dimas K. · Sales','CGK → SIN','18–20 Sep','QUOTE READY'],['TRV-042','Maya R. · Product','CGK → SUB','22 Sep','NEEDS APPROVAL'],['TRV-043','Arif N. · Finance','CGK → BPN','25–27 Sep','BOOKED']]],
  [['EVENT','SIGNAL','SOURCE','SEVERITY','OWNER'],[['SEC-021','After-hours access','Badge logs','MEDIUM','Building Mgmt'],['SEC-022','Visitor pass expired','Front desk','LOW','GA Desk'],['SEC-023','Server room door','Sensor','HIGH','IT Security']]],
  [['ARTICLE','TOPIC','LAST REVIEW','VISIBILITY','OWNER'],[['POL-014','Visitor management','01 Aug 2025','ALL STAFF','GA'],['KB-088','Emergency evacuation','24 Aug 2025','ALL STAFF','HSE'],['POL-031','Vendor onboarding','30 Jul 2025','GA + Finance','Procurement']]]
 ],FINA:[
  [['NO. FAKTUR','VENDOR / ITEM','REF. PO','VALUE','STATUS'],[['INV-2048','PT Sinar Abadi · Hardware','PO-4481','Rp 12.750.000','MATCH'],['INV-2049','CV Cahaya · Logistics','PO-4484','Rp 8.400.000','PARTIAL'],['INV-2050','PT Aman Digital · Licenses','PO-4490','Rp 27.500.000','REVIEW']]],
  [['INVOICE','VENDOR','AMOUNT','APPROVER','QUEUE'],[['INV-2048','PT Sinar Abadi','Rp 12,75 jt','Finance Ops','READY'],['INV-2050','PT Aman Digital','Rp 27,5 jt','Head of IT','WAITING'],['INV-2051','PT Karya Prima','Rp 3,2 jt','GA Lead','ESCALATED']]],
  [['RECEIPT','MERCHANT','CATEGORY','POLICY CHECK','STATUS'],[['RCP-7721','Grab Business · CGK','Travel','Within limit','CLEARED'],['RCP-7722','Hotel Santika · SUB','Lodging','Missing attendee','FLAGGED'],['RCP-7723','Tokopedia · Supplies','Office','Allowed vendor','CLEARED']]],
  [['PERIOD','ACCOUNT','DELTA','MATCHED','OWNER'],[['SEP-W1','AP clearing','Rp 1,2 jt','98.4%','Finance Ops'],['SEP-W1','Corporate card','Rp 340 rb','100%','Nadia S.'],['AUG-MTD','AR control','Rp 4,8 jt','96.1%','AR Team']]],
  [['RULE','SCOPE','TRIGGER','REQUIRED ACTION','VERSION'],[['FR-02','Budget','≥ Rp 10 jt','Clarify cost center','v2.4'],['FR-03','Vendor quotes','≥ Rp 15 jt','Collect 3 quotes','v2.4'],['FR-11','OCR intake','Image invoice','Run local OCR','v1.8']]]
 ],SARA:[
  [['NO. LEAD','CONTACT / COMPANY','CHANNEL','NEED SIGNAL','SEGMENT'],[['LEAD-3001','Budi · PT Nusantara Retail','WhatsApp','Videotron lobby','WARM'],['LEAD-3002','Siti · CV Cahaya Distribusi','Email','Product catalog','COLD'],['LEAD-3003','Andi · PT Arunika Events','Website form','Event package','HOT']]],
  [['OPPORTUNITY','ACCOUNT','SOLUTION','VALUE','STAGE'],[['OPP-091','PT Nusantara Retail','Indoor videotron','Rp 180 jt','DISCOVERY'],['OPP-092','PT Arunika Events','LED rental + crew','Rp 74 jt','PROPOSAL'],['OPP-093','CV Cahaya Distribusi','AV starter kit','Rp 22 jt','QUALIFYING']]],
  [['DEAL','ACCOUNT','ASK','GUARDRAIL','OWNER'],[['NEG-022','PT Nusantara Retail','10% discount','Within band','Raka S.'],['NEG-023','PT Arunika Events','45-day terms','Needs Finance','Maya R.'],['NEG-024','CV Cahaya Distribusi','Free install','Needs approval','Raka S.']]],
  [['ORDER','CUSTOMER','CREDIT CHECK','DEPOSIT','STATUS'],[['ORD-771','PT Nusantara Retail','PASSED','30% received','READY'],['ORD-772','PT Arunika Events','REVIEW','Pending','HOLD'],['ORD-773','CV Cahaya Distribusi','PASSED','50% received','SCHEDULED']]],
  [['ACCOUNT','LAST TOUCH','HEALTH','NEXT STEP','PIPELINE'],[['PT Nusantara Retail','Today · WhatsApp','EXPANDING','Site survey','Rp 180 jt'],['PT Arunika Events','Yesterday · Email','AT RISK','Confirm scope','Rp 74 jt'],['CV Cahaya Distribusi','04 Sep · Call','NURTURE','Send case study','Rp 22 jt']]]
 ]};
 const [rowHeaders,demoRows]=tableSets[active][tab];
 useEffect(()=>{setTab(0);setProofOpen(null);setLogOpen(false)},[active]);
 useEffect(()=>{anime({targets:'.reveal',opacity:[0,1],translateY:[18,0],delay:anime.stagger(45),duration:650,easing:'easeOutCubic'}); anime({targets:'.orb-core',scale:[.86,1],rotate:[-8,0],duration:900,easing:'easeOutElastic(1,.55)'});},[active,tab]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.16}); document.querySelectorAll('.scroll-reveal').forEach(el=>observer.observe(el)); return()=>observer.disconnect()},[active]);
 return <div className="app" style={{'--accent':a.color,'--dark':a.dark}}>
  <aside className="rail"><button type="button" className="brand brand-button" aria-label="Go to Genio homepage" onClick={goHome}><span className="brand-mark">g</span><span>GENIO<span className="muted"> AI</span></span></button><div className="rail-label">AGENTS</div>{Object.entries(agents).map(([key,x])=><button className={'agent '+(active===key?'selected':'')} onClick={()=>setActive(key)} key={key}><span className="agent-dot" style={{background:x.color}}>{x.code}</span><span><b>{key}</b><small>{x.label}</small></span><i>↗</i></button>)}<div className="rail-bottom"><span className="status-dot"/> Human-in-command<br/><small>Every action stays explainable.</small></div></aside>
  <main><header><div className="eyebrow reveal"><span className="pulse"/> GENIO AI AGENTS <span className="slash">/</span> PRODUCT TOUR</div><div className="top-actions"><button type="button" onClick={()=>setModal('map')}>System map</button><button type="button" className="outline" onClick={()=>setModal('walkthrough')}>Request a walkthrough ↗</button></div></header>
   <section className="hero"><div className="hero-copy"><p className="kicker reveal">{a.code} · {a.label.toUpperCase()}</p><h1 className="reveal">{a.tagline}</h1><p className="lede reveal">{a.desc}</p><div className="hero-cta reveal"><button type="button" className="primary" aria-label={`Explore the ${active} operating flow`} onClick={()=>document.getElementById('operating-flow')?.scrollIntoView({behavior:'smooth',block:'start'})}>Explore {active} <span>↓</span></button><span className="micro">Demo cloud · no client data</span></div></div><div className="hero-orbit reveal"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="orb-core" key={active}>{a.code}<small>AGENT</small></div><div className="float-card card-a">JDI Internal AI <b>↗</b><small>back-office intelligence</small></div><div className="float-card card-b">Human approval <b>✓</b><small>always in the loop</small></div></div></section>
   <section className="tour" id="operating-flow"><div className="section-head reveal"><div><p className="kicker">01 / THE OPERATING FLOW</p><h2>One agent. Every stage.<br/><em>Nothing gets lost.</em></h2></div><p className="section-note">Select a tab to see what the team, the front-end agent, and JDI Internal AI do at each step.</p></div>
    <div className="flow-grid"><div className="tab-list reveal" role="tablist" aria-label={`${active} workflow stages`}>{a.tabs.map((t,i)=><button type="button" role="tab" aria-selected={tab===i} aria-controls="workflow-screen" className={tab===i?'active':''} onClick={()=>{setTab(i);requestAnimationFrame(()=>document.getElementById('workflow-screen')?.scrollIntoView({behavior:'smooth',block:'center'}))}} key={t[0]}><span>{t[0]}</span><strong>{t[1]}</strong><i>↗</i></button>)}</div><div className="screen reveal" id="workflow-screen" role="tabpanel" key={`${active}-${tab}`}><div className="screen-top"><span className="window-dots"><i/><i/><i/></span><span>GENIO AI / {active.toLowerCase()} / {a.tabs[tab][0].toLowerCase()}</span><span className="live">● LIVE DEMO</span></div><div className="screen-body"><div className="screen-kicker">{a.tabs[tab][0]} · {a.tabs[tab][1]}</div><h3>{a.tabs[tab][2]}</h3><div className="mock-row"><div className="mock-line long"/><div className="mock-line short"/></div><div className="demo-table"><div className="demo-table-head">{rowHeaders.map(h=><span key={h}>{h}</span>)}</div>{demoRows.map((row,i)=><div className="demo-row" key={row[0]}>{row.map((cell,j)=><span className={j===row.length-1?'status':''} key={`${row[0]}-${j}`}>{cell}</span>)}</div>)}</div><div className="screen-footer"><span><b>T1</b> JDI suggests</span><span><b>T3</b> Team decides</span><span className="arrow">Continue flow →</span></div></div></div></div></section>
   <section className="workflow"><div className="workflow-title reveal scroll-reveal"><p className="kicker">02 / BUILT FOR CONTROL</p><h2>Automation with<br/><em>a visible boundary.</em></h2></div><div className="steps">{a.workflow.map((x,i)=><div className="step reveal scroll-reveal" key={x}><span>0{i+1}</span><div className="step-line"/><h4>{x}</h4><p>{i===0?'Input stays in the flow, not in a black box.':i===1?'The back-office agent turns signals into useful context.':i===2?'The right person keeps the final say.':'Every decision leaves a reason, time, and owner.'}</p></div>)}</div></section>
   <section className="proof"><div className="proof-copy reveal"><p className="kicker">03 / THE GENIO PROMISE</p><h2>More signal.<br/><em>Less operational noise.</em></h2><p>GENIO gives teams an agent that can move quickly without moving beyond its mandate. The interface shows where automation ends and accountability begins.</p><button className="text-link" aria-expanded={logOpen} onClick={()=>setLogOpen(!logOpen)}>See the decision log {logOpen?'↑':'↗'}</button>{logOpen&&<div className="decision-log"><div className="log-head"><span>DECISION REASONING LOG</span><span className="live">● LIVE PROVENANCE</span></div><div className="log-entry"><span className="log-time">06 SEP · 19:15</span><strong>JDI Internal AI · T1</strong><p>Prepared context and a recommended next action for {a.tabs[tab][1]}.</p></div><div className="log-entry"><span className="log-time">06 SEP · 19:18</span><strong>Team owner · T3 · NEEDS APPROVAL</strong><p>Human decision remains required before this workflow can move forward.</p></div><div className="log-foot">Agent · tier · action · rationale · time — captured together.</div></div>}</div><div className="proof-cards">{a.proof.map((x,i)=><div className="proof-wrap reveal" key={x}><button type="button" className={'proof-card '+(proofOpen===i?'open':'')} aria-expanded={proofOpen===i} onClick={()=>setProofOpen(proofOpen===i?null:i)}><span>0{i+1}</span><strong>{x}</strong><i>{proofOpen===i?'−':'✦'}</i></button>{proofOpen===i&&<div className="proof-detail"><b>{x}</b><p>{i===0?`${active} brings ${x.toLowerCase()} into one guided workspace, so every stage has a visible owner and next action.`:i===1?`The front-end agent gathers context, while JDI Internal AI prepares suggestions. The team remains the explicit T3 decision point.`:`Automation can prepare, classify, and explain—but the responsible team keeps final approval for ${active === 'SARA'?'discounts, contracts, credit, and commissions':active === 'FINA'?'payment readiness and exceptions':'operational actions and approvals'}.`}</p><span className="detail-close">Click to collapse ↑</span></div>}</div>)}</div></section>
   <footer><button type="button" className="brand brand-button" aria-label="Go to Genio homepage" onClick={goHome}><span className="brand-mark">g</span><span>GENIO<span className="muted"> AI</span></span></button><span>Operational intelligence, with people in command.</span><span className="company">PT. Jagoan Digital Indonesia</span><span>© 2025 GENIO AI</span></footer>
   {modal&&<div className="modal-backdrop" role="presentation" onClick={()=>setModal(null)}><div className="modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)} aria-label="Close">×</button>{modal==='map'?<><p className="kicker">GENIO / SYSTEM MAP</p><h2>Three agents.<br/><em>One operating model.</em></h2><p className="modal-copy">Choose an agent to jump into its workflow stages and see where automation meets human approval.</p><div className="map-options">{Object.entries(agents).map(([key,x])=><button key={key} onClick={()=>{setActive(key);setModal(null);window.scrollTo({top:0,behavior:'smooth'})}}><span style={{background:x.color}}>{x.code}</span><strong>{key}</strong><small>{x.label} · {x.tabs.length} flows</small><i>↗</i></button>)}</div></>:<><p className="kicker">GENIO / WALKTHROUGH</p><h2>See {active}<br/><em>in your context.</em></h2><p className="modal-copy">Enter an email to capture a demo request. This prototype does not send email yet.</p><div className="walk-form"><input aria-label="Work email" placeholder="Work email" type="email"/><button className="primary" onClick={()=>setModal('sent')}>Capture request <span>→</span></button></div></>}{modal==='sent'&&<div className="sent-state"><b>Demo request captured.</b><span>No email was sent. Connect an email service or backend to enable real follow-up.</span></div>}</div></div>}
  </main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
